api_platform:
    title: 'Fazah'
    description: 'Translations API'
    version: '0.1.0'
    name_converter: 'fazah.api.name_converter'
#    exception_to_status:
#      'Symfony\Component\OptionsResolver\Exception\ExceptionInterface': !php/const:Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
