parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
      connections:
        default:
          # configure these for your database server
          driver: 'pdo_mysql'
          server_version: '5.7'
          charset: utf8mb4

          # With Symfony 3.3, remove the `resolve:` prefix
          url: '%env(resolve:DATABASE_URL)%'
      types:
          message_id: \Eps\Fazah\FazahBundle\Doctrine\Types\MessageIdType
          catalogue_id: \Eps\Fazah\FazahBundle\Doctrine\Types\CatalogueIdType
          project_id: \Eps\Fazah\FazahBundle\Doctrine\Types\ProjectIdType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            Fazah:
                type: xml
                dir: '%kernel.root_dir%/../src/FazahBundle/Resources/config/doctrine'
                prefix: Eps\Fazah\Core\Model
                alias: Fazah
                is_bundle: false
