framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    #session:
    #    # With this config, PHP's native session handling is used
    #    handler_id: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    serializer:
      name_converter: 'serializer.name_converter.camel_case_to_snake_case'
