language: php
php:
  - '7.1'
  - '7.2'
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --no-progress --optimize-autoloader --prefer-dist

script:
  - bin/phpunit --coverage-clover build/logs/clover.xml # --process-isolation

after_success:
  - travis_retry php bin/coveralls
